version: "3"
services:
  node_alice:
    image: dappforce/subsocial-node:$NODE_VERSION
    container_name: $CONT_NODE_ALICE
    restart: on-failure
    command: ./subsocial-node
      -d /data
      --chain df
      --alice
      --port 30333
      --ws-port 9944
      --rpc-port 9933
      --rpc-cors all
      --ws-external
      --rpc-external
      --telemetry-url ws://telemetry.polkadot.io:1024
      --pruning archive
    volumes:
      - $VOLUME_LOCATION/chain_data/alice:/data
    ports:
      - "9944:9944"
      - "9933:9933"
      - "30333:30333"
    networks:
      backend:
        ipv4_address: 172.15.0.21

  node_bob:
    image: dappforce/subsocial-node:$NODE_VERSION
    container_name: $CONT_NODE_BOB
    depends_on:
      - node_alice
    restart: on-failure
    command: ./subsocial-node
      -d /data
      --chain df
      --bob
      --validator
      --port 30334
      --ws-port 9945
      --rpc-port 9934
      --telemetry-url ws://telemetry.polkadot.io:1024
    volumes:
      - $VOLUME_LOCATION/chain_data/bob:/data
    networks:
      backend:
        ipv4_address: 172.15.0.22
