# docker-compose.yml
version: "3"
services:
  web-ui:
    image: dappforce/subsocial-ui:$WEBUI_VERSION
    container_name: $CONT_WEBUI
    restart: on-failure
    environment:
      - SUBSTRATE_URL=$SUBSTRATE_URL
      - OFFCHAIN_URL=$OFFCHAIN_URL
      - ELASTIC_URL=$ELASTIC_URL
      - APPS_URL=$APPS_URL
      - IPFS_URL=$IPFS_READONLY_URL
      - OFFCHAIN_WS=$OFFCHAIN_WS
    networks:
      backend:
        ipv4_address: 172.15.0.2

  nginx:
    build: ../nginx
    image: dappforce/subsocial-proxy:$PROXY_VERSION
    container_name: $CONT_PROXY
    restart: on-failure
    ports:
      - "80:80"
    networks:
      backend:
        ipv4_address: 172.15.0.7
